### ISSUE TITLE
Verify the branch when workflow_dispatch is used

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard-webapp#80] opened 2022-04-22 17:16 UTC
Im not sure we have tested this. If a user manually runs scorecard and select a different branch, does the run succeed, and are the results accepted server-side (they should not)?

/cc @azeemsgoogle @rohankh532

**Comment by azeemshaikh38** [comment] 2022-04-22 17:44
Marking as duplicate of #81

**Closed by azeemshaikh38** 2022-04-22 17:44 UTC
Labels: duplicate
